version: 1


formatters:
  simple:
    format: "%(asctime)s [%(levelname)s] %(message)s"
    datefmt: "%H:%M:%S"

  detailed:
    format: "%(asctime)s [%(levelname)s] [%(name)s] [%(filename)s:%(lineno)d] (%(funcName)s) - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: simple

  file_debug_handler:
    class: logging.FileHandler
    filename: logs/DEBUG.log
    level: DEBUG
    formatter: detailed

loggers:
  # App loggers
  src:
    level: DEBUG
    handlers: [console_handler, file_debug_handler]
    propagate: False

  src.setup:
    level: DEBUG
    handlers: [console_handler, file_debug_handler]
    propagate: False

  src.utils:
    level: DEBUG
    handlers: [console_handler, file_debug_handler]
    propagate: False

  ecmwfapi:
    level: DEBUG
    handlers: [console_handler, file_debug_handler]
    propagate: False

root:
  level: DEBUG
  handlers: [console_handler, file_debug_handler]
  propagate: False
